# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog_log(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 500)
        Dialog.setMinimumSize(QtCore.QSize(480, 500))
        Dialog.setStyleSheet("background-color: rgb(189, 237, 255);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(190, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0,0,0);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 60, 391, 311))
        self.frame.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0,0,0);")
        self.label_2.setObjectName("label_2")
        self.btn_log = QtWidgets.QPushButton(parent=self.frame)
        self.btn_log.setGeometry(QtCore.QRect(130, 220, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_log.setFont(font)
        self.btn_log.setStyleSheet("background-color: rgb(143, 203, 255);\n"
"color: rgb(0,0,0);")
        self.btn_log.setObjectName("btn_log")
        self.line_name = QtWidgets.QLineEdit(parent=self.frame)
        self.line_name.setGeometry(QtCore.QRect(20, 70, 331, 31))
        self.line_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.line_name.setObjectName("line_name")
        self.line_pass = QtWidgets.QLineEdit(parent=self.frame)
        self.line_pass.setGeometry(QtCore.QRect(20, 160, 331, 31))
        self.line_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.line_pass.setObjectName("line_pass")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0,0,0);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Đăng nhập"))
        self.label_2.setText(_translate("Dialog", "Tên đăng nhập/Email/Số điện thoại"))
        self.btn_log.setText(_translate("Dialog", "Đăng nhập"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
