# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_reg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 500)
        Dialog.setMinimumSize(QtCore.QSize(480, 500))
        Dialog.setStyleSheet("background-color: rgb(189, 237, 255);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(190, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0,0,0);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 60, 391, 411))
        self.frame.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"border-color: rgb(68, 120, 201);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0,0,0);")
        self.label_2.setObjectName("label_2")
        self.btn_reg = QtWidgets.QPushButton(parent=self.frame)
        self.btn_reg.setGeometry(QtCore.QRect(140, 300, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_reg.setFont(font)
        self.btn_reg.setStyleSheet("background-color: rgb(143, 203, 255);\n"
"color: rgb(0,0,0);")
        self.btn_reg.setObjectName("btn_reg")
        self.reg_name = QtWidgets.QLineEdit(parent=self.frame)
        self.reg_name.setGeometry(QtCore.QRect(20, 70, 331, 31))
        self.reg_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.reg_name.setObjectName("reg_name")
        self.reg_pass = QtWidgets.QLineEdit(parent=self.frame)
        self.reg_pass.setGeometry(QtCore.QRect(20, 160, 331, 31))
        self.reg_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.reg_pass.setObjectName("reg_pass")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0,0,0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0,0,0);")
        self.label_4.setObjectName("label_4")
        self.conf_pass = QtWidgets.QLineEdit(parent=self.frame)
        self.conf_pass.setGeometry(QtCore.QRect(20, 250, 331, 31))
        self.conf_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.conf_pass.setObjectName("conf_pass")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 360, 200, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0,0,0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.re_log = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.re_log.setStyleSheet("background-color: rgb(143, 203, 255);\n"
"color: rgb(0,0,0);")
        self.re_log.setObjectName("re_log")
        self.horizontalLayout.addWidget(self.re_log)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Đăng ký"))
        self.label_2.setText(_translate("Dialog", "Tên đăng nhập/Email/Số điện thoại"))
        self.btn_reg.setText(_translate("Dialog", "Đăng ký"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu"))
        self.label_4.setText(_translate("Dialog", "Xác nhận lại mật khẩu"))
        self.label_5.setText(_translate("Dialog", "Bạn có tài khoản?"))
        self.re_log.setText(_translate("Dialog", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
